config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :new, :create, :show] 

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:edit, :update]

  resources :posts, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :author_id, presence: true 

    belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

    has_many :post_subs,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

    has_many :subs,
    through: :post_subs,
    source: :sub

end 

app/models/post_sub.rb
class PostSub < ApplicationRecord
    validates :post_id, :sub_id, presence: true 

    belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post

    belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub
    


end 

app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, :user_id, presence: true 

    belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

    has_many :post_subs,
    foreign_key: :sub_id,
    class_name: :PostSub,
    inverse_of: :sub

    has_many :posts,
    through: :post_subs,
    source: :post




end 

app/models/user.rb
class User < ApplicationRecord 
    validates :username, :session_token, :password_digest, presence: true 
    validates :username, uniqueness: true 
    validates :password, length: { minimum: 6, allow_nil: true }

    after_initialize :ensure_session_token!

    has_many :subs,
    foreign_key: :user_id,
    class_name: :Sub

    has_many :posts,
    foreign_key: :author_id,
    class_name: :Post

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        if user.is_password?(password)
            user
        else 
            nil
        end 

    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end 

    def password
        @password
    end 

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)

    end 

    def reset_session_token!
        self.session_token = SecureRandom.base64(64)
        self.save!
        self.session_token
    end 

    

    private 

    def ensure_session_token!
        self.session_token ||= SecureRandom.base64(64) 
    end 

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?, :current_user

    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end 

    def logged_in?
        !!current_user
    end 

    def login!(user)
        @current_user = user
        session[:session_token] = user.reset_session_token!
    end 

    def logout! 
        current_user.reset_session_token!
        session[:session_token] = nil
    end 

    private

    def require_logged_in!
        redirect_to new_session_url unless logged_in? 
    end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
    before_action :check_author, only: [:edit, :update]

    def check_author
        @post = current_user.posts.find(params[:id])
        render json: "Not Allowed", status: 422 unless @post
    end 

    def new
        @post = Post.new
        render :new
    end 

    def create
        debugger
        @post = Post.new(post_params)
        @post.subs_id = params[:subs_id]
        @post.author_id = params[:author_id]

        if @sub.save
            redirect_to sub_url(params[:sub_id])
        else 
            flash[:errors] = @sub.errors.full_messages
            redirect_to sub_url(params[:sub_id])
        end 
    end 

    def edit
        render :edit
    end 

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)

        if @post.save
            redirect_to post_url(params[:id])
        else 
            flash[:errors] = @post.errors.full_messages
            redirect_to sub_url(params[:sub_id])
            #redirect to post show
        end 
    end 

    def show
        @post = Post.find(params[:id])
        render :show
    end 

    def destroy
        @post = current_user.posts.find(params[:id])

        if @post && post.destroy
            redirect_to users_url
        end 
    end 

    private

    def post_params
        params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
    end 

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    # before_action :require_logged_in!, only: [:destroy]

    def new 
        render :new
    end 

    def create
        debugger
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user 
            login!(@user)
            redirect_to subs_url
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_session_url
        end 
    end 

    def destroy
        logout!
        redirect_to new_session_url
    end 


end 

app/controllers/subs_controller.rb
class SubsController < ApplicationController 

    before_action :check_owner, only: [:edit, :update]
    before_action :logged_in?, except: [:index]

    def check_owner
        @sub = current_user.subs.find(params[:id])
        render json: "Not Allowed", status: 422 unless @sub
    end 

    def index 
        @subs = Sub.all
        render :index
    end 

    def new 
        @sub = Sub.new
        render :new
    end 

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = params[:user_id]

        if @sub.save
            redirect_to user_url(params[:user_id])
        else 
            flash[:errors] = @sub.errors.full_messages
            redirect_to user_url(params[:user_id])
        end 

    end 

    def show
        @sub = Sub.find(params[:id])
        # LIST POSTS IN SHOW VIEW
        # @sub = current_user.subs.find(params[:id])
        render :show
    end 

    def edit
        render :edit
    end 

    def update
        @sub = Sub.find(params[:id])
        @sub.update(user_params)

        if @sub.save
            redirect_to user_url(params[:user_id])
        else 
            flash[:errors] = @sub.errors.full_messages
            redirect_to user_url(params[:user_id])
        end 
    end 

    private

    def sub_params
        params.require(:sub).permit(:title, :description, :user_id)
    end 


end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    before_action :require_logged_in!, only: [:index, :show]

    def index
        @users = User.all
        render :index
    end 


    def new
        @user = User.new
        render :new
    end 

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to subs_url
        else 
            flash[:errors] = @user.errors.full_messages
            render :new
        end 

    end 

    def show
        @user = User.find(params[:id])

        if @user 
            redirect_to user_url(@user)
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to users_url
        end 

    end 

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end 



end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if logged_in? %>
      <ul>
        <li>
          <%= current_user.username %>

          <form action="<%= new_sub_url %>" method="GET">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <button>Create a Sub!</button>
          </form>

          <form action="<%= subs_url %>" method="GET">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <button>All Subs</button>
          </form>
          
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <button>Sign Out</button>
          </form>

      </li>
    </ul>
    <% else %>
     <form action="<%= new_session_url %>" method="GET">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <button>Sign In</button>
      </form>
    <% end %>

    

    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New Post!</h1>

   <form action="<%= posts_url %>" method="POST">
         <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label>Name 
        <input name="post[title]" value="<% @post.title %>">
        </label>
        <br>

        <label>URL 
        <input name="post[url]" value="<% @post.url %>">
        </label>
        <br>

        <label>Content 
        <input name="post[content]" value="<% @post.content %>">
        </label>
        <br>

        <input type="hidden" name="post[sub_ids][]" value="">
            <% Sub.all.each do |sub| %>
            <label>
                <input 
                 type="checkbox"
                 name="post[sub_ids][]"
                 value="<%= sub.id %>"
                 <%= "checked" if @post.sub_ids.include?(sub.id) %> 
                 >
                 <%= sub.title %>
            </label>
            <br>
               
            <% end %>

            <button>Submit</button>

    </form>

app/views/posts/show.html.erb
<h1><%= @post.title %> by <%= @post.author.username %>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
<% @subs.each do |sub| %>
    <li>
    <a href="<%= sub_url(sub) %>"><%= sub.title %>
    </li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>

    <form action="<%= subs_url %>" method="POST">
         <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label>Name 
        <input name="sub[title]" value="<% @sub.title %>">
        </label>
        <br>
        <label>Description 
        <input name="sub[description]" value="<% @sub.description %>">
        </label>

        <button> Submit! </button>

    </form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<% if @sub.description%>
    <strong><p>Description</p></strong>
    <p><%= @sub.description %></p>
<% end %>

<form action="<%= new_post_url %>" method="GET">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <button>Make New Post!
    </button>
</form>
<ul>
    <li>
        <% @sub.posts.each do |post| %>
            <a href="<%= post_url(post) %>"><%= post.title  %></a>
        <% end %>
    </li>
</ul>

app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Username
        <input name="user[username]" value="<% @user.username %>">
    </label>

    <label>Password
        <input type="password" name="user[password]">
    </label>

    <button>Create User</button>

    

</form>